### ISSUE TITLE
Design Docs - Database Schema

### ISSUE THREAD

**Issue by huangs2022672** [keginzburg/webflix#3]
Hi Kyle, great job on the schema!!

# Database Schema
​
- [x] Contains correct datatypes
- [x]  Contains appropriate constraints/details
    - [x]  primary key
    - [x]  not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
​
### Comments

* for profiles, have you thought about making profile names unique to the user?

* for videos
  * should runtime be a string?
  * a video shouldn't keep track of it's number of likes, the likes table should be tracking this. You wouldn't want to do this because every time someone likes a video you'd have to update both the videos and likes table and the two would need to match up. you'd want to grab all the likes from the video and count it see how many likes a video has.
  * do you want your videos to belong to more than one genre? if so, think about how to go about this. if not, you can keep genre as a string and remove the genres table.

* for mylists, you'd want each profile to have a video on it's mylist once

**Comment by keginzburg** [comment]
Hey Sammy! I've added some edits:

1. For unique profile names for each respective user, I've given it a combination index [:user_id, :name] with uniqueness.

2. I've switched runtime to an integer data type.

3. I've nixed the likes column in my video table and have a video's likes tracked via the likes join table between videos and profiles.

4. For MyLists, I've also added a combination index [:video_id, :profile_id] with uniqueness to ensure that profiles can MyList a video once.

5. On your point about genres, my intention is to make it so that videos are categorized under one genre (for the time being, potential for updating this as a bonus down the line). I had wanted to keep a genre table, so I could seed my database with fixed genres as there is no CRUD functionality when it comes to videos and their genre categorization. Is there any downside to keeping a genre table and giving videos a genre id that references it?

**Comment by huangs2022672** [comment]
Hi Kyle, everything looks great!! and /w regards to genre, I wasn't sure what you wanted to do with it at first, but if you do plan to expand genre later on it is fine to keep what you have. If you didn't, it just seems weird to have a separate table when it can be stored in the videos table.

**Comment by keginzburg** [comment]
Awesome, thanks Sammy!
