### ISSUE TITLE
Design Docs - Sample State

### ISSUE THREAD

**Issue by huangs2022672** [keginzburg/webflix#5]
Great job Kyle! very very minor note at the bottom

# Sample State
​
- [x] State shape is flat!
- [x]  State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language `(```javascript...```)`. This will display the state as a code block instead of a giant line of text
    - [x]  Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka `comments` inside of `posts`
        - Some info from other tables is ok, for instance:
            - the author username and imageurl for a post. basically any info that the user can't change
            - like count and a boolean on whether the user likes the post instead of a likes slice
​
### Comments

- not sure how necessary it is to keep an array of profileIds in the user pojo, what would be a use case?

**Comment by keginzburg** [comment]
Hey Sammy, I wasn't sure how I'd best manage those profiles and populate my profiles modal with a user's profiles, so I figured maybe storing them in the state that way would be beneficial. But my GET /api/users/:id/profiles route exists for a reason on second thought, so maybe the profileIds in my user pojo is redundant. To be honest, I'm still not entirely comfortable with the idea of managing my state with this kind of project since there are more variables to consider, but I'm sure it'll start to make sense as I dive in.
