### ISSUE TITLE
Splash/Auth

### ISSUE THREAD

**Issue by huangs2022672** [keginzburg/webflix#7]
Hi Kyle, awesome job on splash/auth. some should do's and can ignore's below.

## should do's:
* when logged out:
  * should not be able to go to #/manageprofiles

* when logged in:
  * I think it's fine to keep the sign out button in profiles permanently, add styling

* login page:
  * Webflix logo should link back to root
  * add a demo user login button on the Sign In form

* signup page:
  * Webflix logo should link back to root
  * password placeholder missing
  * on a taller screen the footer is not all the way at the bottom

* error rendering:
  * error messages persist when page is refreshed

## stuff that you can ignore or implement if you want:

* splash:
  * consider moving the demo login button to the top right (personal opinion)
  * email placeholders shrinks above when input is selected or if there's text
  * Get Started checks valid email format, button has slight hover over effect
  * on a wider screen splash bg image repeats
  * text that are links are underlined when hovered over

* login page:
  * email and password placeholders shrinks above when input is selected or if there's text
  * text that are links are underlined when hovered over
  * the selected input has a lighter bg color

* signup page: 
  * email and password placeholders shrinks above when input is selected or if there's text
  * slight hover effect on button

**Comment by keginzburg** [comment]
Hey Sammy,

1. I added a Protected Route for my /ManageProfiles route along with my /browse and /watch routes.
2. I've kept the sign out button on the profiles modal with some styling (oddly enough Netflix doesn't have this which is surprising to me).
3. Webflix logo links back to root on signup and login pages now
4. I was wondering if it's worth adding a demo user button on the login page because I figured a user would only check the login link if they had an existing account. If you still think it's a "should do", then please let me know.
5. Added a password placeholder to signup page.
6. As of now, I've added some absolute positioning for the footer to always be at the bottom of the window and changed screen sizes on other monitor, so I think this is fixed.
7. Errors now clear on page refresh.

Otherwise, will definitely keep they extra issues in mind. Thanks!

**Comment by huangs2022672** [comment]
Hi Kyle,

You're right, since you already have a demo user on your splash, it's fine to not have one on the sign in form.
The logout button seems not to be working now.

**Comment by huangs2022672** [comment]
found that signing up did not require email format xxx@xxx.xxx
