### ISSUE TITLE
MVP #1 - Profiles 

### ISSUE THREAD

**Issue by huangs2022672** [keginzburg/webflix#8]
Hi Kyle, profiles is all set! just some very minor things I saw, get to them only if you have time.

1. think about capping number of profiles to 4, I was able to keep adding profiles until the add profile option was off the page.
2. the first time I'm editing a profile the default image does not load/or is of a previously selected image.
3. when canceling a edit profile, the name persists when creating a new profile, the image persist when editing a different profile
4. logo should link back to /browse
5. was able to create a profile with no name ""

**Comment by keginzburg** [comment]
Hey Sammy! Hope all is going well. I've added the following:

1. Profiles cap out at 4 with error messages.
2. I believe the default image is set for icon choices now.
3. When canceling a profile, the name's and icon's should not persist and only reflect the current profile being edited.
4. I think I've added full error handling and messages for profile names needing to be between 1 and 8 characters.
5. On your logo linking back to /browse note, I'd actually like to make the logo here purely aesthetic since we're already technically routed to /browse when choosing profiles and the user should not be able to see titles until they log into a profile. Plus, the user is logged in at this point, so I can't make it route back to the root without logging out the user which is provided by the sign out button in the header.

Again, you're the best. Thanks for everything and hope all is well!
